export const customerConstants = {
    LOGIN_REQUEST: 'CUSTOMER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'CUSTOMER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'CUSTOMER_LOGIN_FAILURE',

    REGISTER_REQUEST: 'CUSTOMER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'CUSTOMER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'CUSTOMER_REGISTER_FAILURE',

    LOGOUT: 'CUSTOMER_LOGOUT'
}